# Poker AI Configuration

# Game parameters
game:
  variant: "NT"  # No-Limit Texas Hold'em
  starting_stack: 10000
  small_blind: 50
  big_blind: 100
  player_count: 10  # 9 AI + 1 human
  timeout_seconds: 5  # Timeout for betting decisions

# Neural Network parameters
model:
  # Input features
  input_dim: 658  # Total features: hand_cards(52) + board_cards(52) + player_actions(6*9) + pot(1) + stacks(10) + position(10) + blinds(1)
  
  # Network architecture
  layers:
    - type: "dense"
      units: 512
      activation: "relu"
    - type: "dense"
      units: 256
      activation: "relu"
    - type: "dense"
      units: 128
      activation: "relu"
    - type: "dense"
      units: 3  # fold, call, raise
      activation: "linear"
  
  # Training parameters
  learning_rate: 0.0001
  batch_size: 64
  optimizer: "adam"

# Evolutionary parameters
evolution:
  population_size: 50
  generations: 1000
  tournament_size: 5
  mutation_rate: 0.1
  crossover_rate: 0.7
  elitism_count: 5

# Training parameters
training:
  episodes_per_generation: 100
  hands_per_episode: 100
  checkpoint_frequency: 10  # Save model every N generations
  eval_frequency: 5  # Evaluate model every N generations
  
# Resource management
resources:
  use_gpu: true
  cpu_threads: -1  # -1 means use all available cores
  memory_limit_gb: 8  # Limit memory usage
  
# Logging
logging:
  level: "INFO"
  save_path: "logs/"
  tensorboard: true